language: python
python:
  - "3.6"

# Branches to enbale CI.
branches:
  only:
    - master


deploy:
  provider: heroku
  api_key: $HEROKU_PRODUCTION_API_KEY
  app: HEROKU_APP_NAME

notifications:
    slack: bisoncorps:urrq42VfAo4zJP2r6lH2dU8Y