language: python
python:
  - "3.6"

addons:
  sonarcloud:
    # create sonar connection for code health analysis
    organization: "deven96-github" 
    token:
      secure: $SONAR_TOKEN

# Branches to enbale CI.
branches:
  only:
    - master

script: sonar-scanner

deploy:
  provider: heroku
  api_key: $HEROKU_PRODUCTION_API_KEY
  app: $HEROKU_APP_NAME
  run:
    - "python init_imagenet.py"

notifications:
    slack: bisoncorps:urrq42VfAo4zJP2r6lH2dU8Y