language: python
sudo: required

python:
  - "3.6"

# Branches to enbale CI.
branches:
  only:
    - master

script: python tests.py
after_script: 
# build docs on github pages
- ./docs.sh

deploy:
  provider: heroku
  api_key: $HEROKU_PRODUCTION_API_KEY
  app: $HEROKU_APP_NAME


notifications:
# slack channel notification
    slack: bisoncorps:urrq42VfAo4zJP2r6lH2dU8Y