language: python
sudo: required

python:
  - "3.6"

# Branches to enbale CI.
branches:
  only:
    - master

install:
  - pip install -r requirements.txt

script:
  # to replace with tests
  - python setup.py install

deploy:
  provider: heroku
  api_key: $HEROKU_PRODUCTION_API_KEY
  app: $HEROKU_APP_NAME

after_deploy:
  - ./docs.sh

notifications:
# slack channel notification
    slack: bisoncorps:urrq42VfAo4zJP2r6lH2dU8Y