language: python
sudo: required

python:
  - "3.6"

addons:
  sonarcloud:
    # create sonar connection for code health analysis
    organization: "deven96-github" 
    token:
      secure: $SONAR_TOKEN

git:
    submodules: false

# Branches to enbale CI.
branches:
  only:
    - master

deploy:
  provider: heroku
  api_key: $HEROKU_PRODUCTION_API_KEY
  app: $HEROKU_APP_NAME

script: 
- sonar-scanner
# build docs on github pages
- ./docs.sh


notifications:
# slack channel notification
    slack: bisoncorps:urrq42VfAo4zJP2r6lH2dU8Y